# ---------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# ---------------------------------------------------------


parameters:
- name: pythonVersion
  displayName: Python Version
  type: string
  default: 3.7
  values:
    - 3.7
    - 3.8
    - 3.9
- name: cliSource
  displayName: Installation source for CLI
  type: string
  default: LatestRelease
  values:
    - LatestRelease
    - LatestDev
    - LatestTest
- name: sdkSource
  displayName: Installation source for Python SDK
  type: string
  default: LatestRelease
  values:
    - LatestRelease
    - LatestDev
    - LatestTest
- name: subscriptionName
  type: string
- name: configFileArtifact
  type: string
  default: WorkspaceConfiguration
- name: poolImage
  type: string
  default: ubuntu-latest
- name: testRunType
  type: string
  default: E2E
  values:
    - E2E
    - Notebooks


jobs:
  - job:
    displayName: "Run ${{parameters.testRunType}} tests"
    
    pool:
      vmImage: ${{parameters.poolImage}}

    steps:
      - template: python-preparation-step-template.yaml
        parameters:
          pythonVersion: ${{parameters.pythonVersion}}
          cliSource: ${{parameters.cliSource}}
          sdkSource: ${{parameters.sdkSource}}
          subscriptionName: ${{parameters.subscriptionName}}

      - task: DownloadPipelineArtifact@2
        displayName: "Download configuration Artifact ${{parameters.configFileArtifact}}"
        inputs:
          artifact: ${{parameters.configFileArtifact}}
          path: $(Build.SourcesDirectory)

      - script: ls -p $(Build.SourcesDirectory)
        displayName: "Show sources directory"

      - ${{ if eq(parameters.testRunType, 'E2E')}}:
        - task: AzureCLI@2
          displayName: Run E2E tests
          inputs:
            azureSubscription: "${{parameters.subscriptionName}}"
            addSpnToEnvironment: true
            scriptType: pscore
            scriptLocation: scriptPath
            scriptPath: scripts/Run-E2E-Tests.ps1
            failOnStandardError: false # Since the new CLI writes stuff there

      - ${{ if eq(parameters.testRunType, 'Notebooks')}}:
        - task: AzureCLI@2
          displayName: Run Notebook tests
          inputs:
            azureSubscription: "${{parameters.subscriptionName}}"
            addSpnToEnvironment: true
            scriptType: pscore
            scriptLocation: scriptPath
            scriptPath: scripts/Run-Notebook-Tests.ps1
            failOnStandardError: false # Since the new CLI writes stuff there

      - task: PublishTestResults@2
        displayName: Publish Test Results
        inputs:
          testResultsFormat: JUnit
          testResultsFiles: "**/junit.xml"
          searchFolder: "$(System.DefaultWorkingDirectory)"
        condition: always()