# ---------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# ---------------------------------------------------------


parameters:
- name: pythonVersion
  displayName: Python Version
  type: string
  default: 3.7
  values:
    - 3.7
    - 3.8
    - 3.9
- name: cliSource
  displayName: Installation source for CLI
  type: string
  default: LatestRelease
  values:
    - LatestRelease
    - LatestDev
- name: sdkSource
  displayName: Installation source for Python SDK
  type: string
  default: LatestRelease
  values:
    - LatestRelease
    - LatestDev
- name: subscriptionName
  type: string
- name: configFileDirectory
  type: string
  default: configFiles
- name: configFileArtifact
  type: string
  default: WorkspaceConfiguration
- name: poolImage
  type: string
  default: ubuntu-latest


jobs:
  - job:
    displayName: "Run Python tests"
    
    pool:
      vmImage: ${{parameters.poolImage}}

    steps:
      - template: python-preparation-step-template.yaml
        parameters:
          pythonVersion: ${{parameters.pythonVersion}}
          cliSource: ${{parameters.cliSource}}
          sdkSource: ${{parameters.sdkSource}}
          subscriptionName: ${{parameters.subscriptionName}}
